spring:
  profiles:
    active:
    - dev
---
spring:
  application:
    profiles: dev     # 开发环境
    name: microservicecloud-config-atguigu-dev
---
spring:
  application:
    profiles: test     # 测试环境
    name: microservicecloud-config-atguigu-test
# 请保存为UTF-8格式